// <auto-generated />
using System.Collections.Generic;
using EfValueObjectAsJson.DemoApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfValueObjectAsJson.DemoApi.Migrations
{
    [DbContext(typeof(OrderContext))]
    partial class OrderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EfValueObjectAsJson.DemoApi.Data.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("EfValueObjectAsJson.DemoApi.Data.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.ComplexCollection(typeof(List<Dictionary<string, object>>), "Items", "EfValueObjectAsJson.DemoApi.Data.Order.Items#OrderItem", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<int>("Quantity");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Item", "EfValueObjectAsJson.DemoApi.Data.Order.Items#OrderItem.Item#Item", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<int>("Id");

                                    b2.Property<string>("Name")
                                        .IsRequired();

                                    b2.Property<decimal>("Price");
                                });

                            b1.ToJson("Items");
                        });

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
